"""create users games posts

Revision ID: 5a6f37e6061e
Revises: 
Create Date: 2026-01-19 20:35:42.712967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6f37e6061e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.String(length=36), nullable=False, comment='ゲームID(UUID)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='ゲーム名'),
    sa.Column('summary', sa.String(length=500), nullable=True, comment='ゲームの概要'),
    sa.Column('package_photo', sa.String(length=500), nullable=False, comment='パッケージ画像'),
    sa.Column('genre', sa.String(length=50), nullable=True, comment='ゲームジャンル'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='登録日'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新日'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False, comment='ユーザーID(UUID)'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='ユーザー名'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='登録日'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新日'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.String(length=36), nullable=False, comment='レビューID(UUID)'),
    sa.Column('game_id', sa.String(length=36), nullable=True, comment='ゲームID'),
    sa.Column('title', sa.String(length=30), nullable=False, comment='投稿タイトル'),
    sa.Column('body', sa.String(length=300), nullable=False, comment='投稿本文'),
    sa.Column('screenshot_url', sa.String(length=300), nullable=False, comment='スクリーンショットURL'),
    sa.Column('created_user_id', sa.String(length=36), nullable=False, comment='ユーザーID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='投稿日'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新日'),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('users')
    op.drop_table('games')
    # ### end Alembic commands ###
